version: "3.9"

services:
  db:
    image: postgres:17
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: anspire
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: fastapi_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      db: 
        condition: service_healthy
    environment:
      DATABASE_URL_ASYNC: ${DATABASE_URL}
      DATABASE_URL_SYNC: ${ALEMBIC_DATABASE_URL}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
