"""timestamp timezone

Revision ID: 861d735ce25d
Revises: bd613db110e0
Create Date: 2025-06-15 17:26:25.013852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '861d735ce25d'
down_revision: Union[str, None] = 'bd613db110e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balance_user_id_fkey'), 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key(op.f('balance_user_id_fkey'), 'balance', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
